---
- hosts: localhost
  collections:
    - kubernetes.core
  tasks:
    - name: Create a pod
      k8s:
        state: present
        definition:
        api_version: v1
        kind: Pod
        metadata:
            name: "utilitypod-1"
            namespace: default
            labels:
                app: galaxy
        spec:
            containers:
            - name: utilitypod
              image: busybox
